server {
    listen ${PORT};
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Route backend API calls to Go on port 8085
    location /v1 {
        proxy_pass http://127.0.0.1:8085;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Serve React static files and handle React Router (SPA) client-side routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}